spring:
  application:
    name: interview-task
  datasource:
    url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    hikari:
      maximum-pool-size: 25
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-bigdecimal-as-plain: true

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

wallet:
  demo-data:
    enabled: true
  withdrawal:
    scheduler:
      enabled: true

logging:
  pattern:
    correlation: "[%X{correlationId:-}] "
  level:
    com.finrax.interview_task: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

---
spring:
  config:
    activate:
      on-profile: sql

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
